# Generated by Django 6.0.4 on 2026-04-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_version',
        ),
    ]
